config/routes.rb
Blocmarks::Application.routes.draw do
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up" # remind me what the :as part is again....
  resources :users, except: [:index]
  resources :sessions
  resources :bookmarks, except: [:index] do
    resources :favorites, only: [:create, :destroy]
  end

  get 'community', to: 'hashtags#index', as: :hashtags
  get 'tags/:id', to: 'hashtags#show', as: :hashtag
  get 'favorites/:id', to: 'users#favorites', as: :user_favorites
  get 'my_library/:id', to: 'users#my_library', as: :user_library
 
  root to: 'welcome#index'

 

end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  attr_accessible :description, :title, :url, :tags_string
  belongs_to :user
  has_many :tagmaps
  has_many :hashtags, :through => :tagmaps, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :url, :format => URI::regexp(%w(http https)), presence: true
  default_scope order('created_at Desc')
  scope :favorited, lambda { |user| joins(:favorites).where('favorites.user_id' => user.id) }

  before_save :get_embedly_data
  serialize :metadata, Hash

  def tags_string
    self.hashtags.map {|h| h.tag}.join(" ")
  end

  def tags_string=(values)
    # this is how you change the relation - right through the join table, without having to manipulate it directly
    self.hashtags = values.split(" ").map { |s| Hashtag.where(tag: s).first_or_create }
  end

  def self.create_through_email(user_email, tags, url)
    if user = User.where(email: user_email).first
      @bookmark = user.bookmarks.create(url: url, tags_string: tags) 
    end
  end

  private

  def get_embedly_data
    embedly_url_service = EmbedlyUrlService.new(self.url)
    self.metadata = embedly_url_service.as_hash
    self.title = embedly_url_service.title
    self.description = embedly_url_service.description
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def show
    @bookmark = Bookmark.find(params[:id])
  end

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = current_user.bookmarks.build(params[:bookmark])
    if @bookmark.save
      flash[:notice] =  "Your bookmark has been saved."
      redirect_to hashtags_path
    else
      flash[:error] = "There was a problem saving your bookmark, please try again."
      render :new
    end
  end

  def edit
    @bookmark = Bookmark.find(params[:id])
  end

  def update
    @bookmark = Bookmark.find(params[:id])
    if @bookmark.update_attributes(params[:bookmark])
      redirect_to @bookmark, notice: "Your bookmark has been updated."
    else
      flash[:error] = "There was a problem updating your bookmark, please try again."
      render :edit
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    if @bookmark.destroy
      redirect_to hashtags_path, notice: "Bookmark was deleted successfully."
    else
      flash[:error] = "There was a problem deleting the bookmark"
      render :show
    end
  end

end

app/views/bookmarks/_bookmark.html.haml
.col-md-2
  %a{href: "#{bookmark.url}", target: "_blank"} 
    = bookmark_thumbnail(bookmark.metadata)
  %p 
    %strong Title:
    #{bookmark.metadata[:title]}
  %br/ 
  Saved by #{bookmark.user.name} #{time_ago_in_words(bookmark.created_at)} ago
  - if can? :delete, bookmark
    = link_to "Delete", bookmark, method: :delete
  - if can? :edit, bookmark
    = link_to "Edit", edit_bookmark_path(bookmark)
  - if current_user 
    = render partial: "favorites/favorite", locals: { bookmark: bookmark }

app/views/bookmarks/_form.html.haml
= form_for bookmark, html: {class: 'form-horizontal' } do |f| 
  - if bookmark.errors.any?
    .alert.alert-block
      %h4= "There are #{pluralize(bookmark.errors.count, "error")}"
      %ul 
        - bookmark.errors.full_messages.each do |msg|
          %li= msg 
  = control_group_tag(bookmark.errors[:url]) do
    = f.label :url, class: 'control-label'
    .controls
      = f.text_field :url
  = control_group_tag(bookmark.errors[:tags_string]) do
    = f.label :tags_string, class: 'control-label'
    .controls
      = f.text_field :tags_string
  .control-group
    .controls
      = f.submit "Save", class: 'btn'

app/views/bookmarks/_form_edit.html.haml
= form_for bookmark, html: {class: 'form-horizontal' } do |f| 
  - if bookmark.errors.any?
    .alert.alert-block
      %h4= "There are #{pluralize(bookmark.errors.count, "error")}"
      %ul 
        - bookmark.errors.full_messages.each do |msg|
          %li= msg 
  = control_group_tag(bookmark.errors[:url]) do
    = f.label :url, class: 'control-label'
    .controls
      = f.text_field :url
  = control_group_tag(bookmark.errors[:title]) do
    = f.label :title, class: 'control-label'
    .controls
      = f.text_field :title
  = control_group_tag(bookmark.errors[:description]) do
    = f.label :description, class: 'control-label'
    .controls
      = f.text_area :description, rows: 8
  = control_group_tag(bookmark.errors[:tags_string]) do
    = f.label :tags_string, class: 'control-label'
    .controls
      = f.text_field :tags_string
  .control-group
    .controls
      = f.submit "Save", class: 'btn'

app/views/bookmarks/edit.html.haml
%h1 Bookmarks#edit
= render partial: 'form_edit', locals: { bookmark: @bookmark }

app/views/bookmarks/new.html.haml
%h1 New Bookmark
.row
  .span8
    = render partial: 'form', locals: { bookmark: @bookmark }

app/views/bookmarks/show.html.haml
%h1 Bookmarks#show
%p= @bookmark.url
%p= @bookmark.title
%p= @bookmark.description

= link_to "Delete Bookmark", @bookmark, method: :delete, class: 'btn btn-large btn-block btn-danger', confirm: 'Are you sure you want to delete this post?'