config/routes.rb
Blocmarks::Application.routes.draw do
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up" # remind me what the :as part is again....
  resources :users, except: [:index]
  resources :sessions
  resources :bookmarks, except: [:index] do
    resources :favorites, only: [:create, :destroy]
  end

  get 'community', to: 'hashtags#index', as: :hashtags
  get 'tags/:id', to: 'hashtags#show', as: :hashtag
  get 'favorites/:id', to: 'users#favorites', as: :user_favorites
  get 'my_library/:id', to: 'users#my_library', as: :user_library
 
  root to: 'welcome#index'

 

end

app/models/hashtag.rb
class Hashtag < ActiveRecord::Base
  attr_accessible :tag
  has_many :tagmaps
  has_many :bookmarks, :through => :tagmaps
  validates :tag, presence: true, uniqueness: true
end

app/controllers/hashtags_controller.rb
class HashtagsController < ApplicationController
  def index
    @hashtags = Hashtag.all
  end

  def show
    @hashtag = Hashtag.find(params[:id])
    @bookmarks = @hashtag.bookmarks.paginate(page: params[:page], per_page: 3)
  end
end

app/views/hashtags/index.html.haml
%h1 Bookmarks from the Blocmarks Community

- @hashtags.each do |hashtag|
  - unless hashtag.bookmarks.empty?
    %div.row
      %h3= link_to hashtag.tag, hashtag_path(hashtag) 
      = render partial: "bookmarks/bookmark", collection: hashtag.bookmarks.limit(5)

app/views/hashtags/show.html.haml
%h1 All items tagged: #{@hashtag.tag}
%br/ 
%ul 
  = render @bookmarks
= will_paginate @bookmarks