config/routes.rb
Blocmarks::Application.routes.draw do
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up" # remind me what the :as part is again....
  resources :users, except: [:index]
  resources :sessions
  resources :bookmarks, except: [:index] do
    resources :favorites, only: [:create, :destroy]
  end

  get 'community', to: 'hashtags#index', as: :hashtags
  get 'tags/:id', to: 'hashtags#show', as: :hashtag
  get 'favorites/:id', to: 'users#favorites', as: :user_favorites
  get 'my_library/:id', to: 'users#my_library', as: :user_library
 
  root to: 'welcome#index'

 

end

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "danger"}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default{role: "navigation"}
  / Brand and toggle get grouped for better mobile display
  .navbar-header
    %button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", type: "button"}
      %span.sr-only Toggle navigation
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    = link_to 'Blocmarks', root_path, class: 'navbar-brand'
  / Collect the nav links, forms, and other content for toggling
  #bs-example-navbar-collapse-1.collapse.navbar-collapse
    %ul.nav.navbar-nav
      %li
        = link_to "Community", hashtags_path
      - if current_user
        %li
          = link_to "My Library", user_library_path(current_user)
        %li 
          = link_to "Favorites", user_favorites_path(current_user)
    %ul.nav.navbar-nav.navbar-right
      %li
        - if current_user
          %p.navbar-text.navbar-right
            Welcome
            = link_to current_user.name, edit_user_path(current_user), class: 'navbar-link'
      %li.dropdown
        %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
          Account Actions
          %b.caret
        %ul.dropdown-menu
          - if current_user
            %li 
              = link_to "Edit account", edit_user_path(current_user)
            %li 
              = link_to "Sign out", log_out_path
          - else
            %li 
              = link_to "Sign in", log_in_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Blocmarks'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Blocmarks'}"}
    = stylesheet_link_tag "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    .container
      .row
        .col-md-2
          .left-nav
            - if current_user
              .btn-group
                %button.btn.btn-primary.dropdown-toggle{"data-toggle" => "dropdown", type: "button"}
                  Add to Blocmarks
                  %span.caret
                %ul.dropdown-menu{role: "menu"}
                  %li
                    = link_to "New Bookmark", new_bookmark_path
        .col-md-10
          %main{:role => "main"}
            .container
              = render 'layouts/messages'
              = yield